# Generated by Django 3.2 on 2022-04-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='lecturerId',
            new_name='lecturer_details',
        ),
    ]
