# Generated by Django 3.2 on 2022-04-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_lecturerid_class_lecturer_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='course',
        ),
    ]
