# Generated by Django 3.2 on 2022-04-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220411_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='classLists',
            field=models.ManyToManyField(blank=True, to='main.Class'),
        ),
    ]
