# Generated by Django 3.2 on 2022-04-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_studentenrollment_gradetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='gradeTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
