export {default as Home } from './Home'
export {default as Class } from './Class'
export {default as Courses } from './Courses'
export {default as Lecturers } from './Lecturers'
export {default as Semester } from './Semester'
export {default as Students } from './Students'
export {default as EnrollLists } from './EnrollLists'